title: DDtKey's blog
subtitle: Personal website & blog
description: >- # this means to ignore newlines until "baseurl:"
  DDtKey's personal website & blog.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: About
      url: /about

# i8n
languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Artem Medvedev
author_bio: >-
  Hi, my name is Artem Medvedev. I'm a software developer (Rust, Java, Typescript). <br/>
  I'm a big fan of software development, it's more than just a job for me. <br/>
  I always strive for professional growth, gaining new knowledge and opportunities ðŸš€ <br/>
author_email: "ddttkey@gmail.com"
author_location: Russia
author_website_url: "https://ddtkey.github.io"
typewrite-text: Welcome to my personal website!

# Experiences
author_work_experiences:
            - company_name: Luxoft
              company_logo: luxoft.png
              company_url: https://www.luxoft.com/
              designation: Lead Software Engineer
              description: Worked on various Luxoft projects
              visibility: true
            - company_name: Evotor
              company_logo: evotor.png
              company_url: https://evotor.ru/
              designation: Senior Java Software Engineer
              description: >-
                Designed and developed horizontally scalable web services within the Evotor.PAY payment service.
                Made integration with banking systems via API.

                Used technologies: Spring (MVC, Data, Messaging, Websocket), AWS S3, Kafka, Oracle DB, Angular
                and etc.
              visibility: true
            - company_name: Texuna Technologies
              company_logo: texuna.png
              company_url: https://texuna.com/
              designation: Java Software Engineer
              description: >-
                Developed web services (in close collaboration with business analysts and QA engineers), which are
                actively used in the UK education sector.
                Worked in strict compliance with the Privacy Policy (ÑˆDPR).

                Technologies used: Spring, AWS, Angular, d3js, Wicket, PostgreSQL, OLAP (MDX) and etc.
              visibility: true
            - company_name: Simplex-Sofware
              company_logo: simplex-software.png
              company_url: https://simplex-software.ru/
              designation: Java Developer
              description: >-
                Developed projects in accordance with the terms of reference (server side, including the development
                of blockchain solutions), using the following technologies: Spring Framework, Wicket, ZK Framework,
                Hibernate, XPath, web3j.

                Participated in discussions on application architecture.
                Conducted code reviews, helped and lectured colleagues.
              visibility: true

# Education
author_education_details:
              - college_logo: mgou-logo.png
                college_name: MSRU (Moscow State Regional University)
                college_url: https://mgou.ru/
                college_degree: Project Manager
                description: Bachelor's degree
                visibility: true

# Projects
#author_project_details:
#              - project_thumbnail: gamershub.png
#                project_title: Gamers Hub
#                project_description: A Platform built for Gamers and Game Devs
#                project_url: https://gamershub.in
#                visibility: true

# social links
twitter_username: DDttKey
github_username:  DDtKey
facebook_username: 
linkedin_username: ddtkey
behance_username: 
instagram_username: ddttkey
medium_username: 
telegram_username: DDtKey
dribbble_username: 
flickr_username: 

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname:
hyvor_talk_website_id:

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# formspree (contact form)
formspree_email: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin
  - jekyll-polyglot

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

# fix polyglot for jekyll 4+
sass:
  sourcemap: never

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
