title: DDtKey's blog
subtitle: Personal website & blog
description: >- # this means to ignore newlines until "baseurl:"
  DDtKey's personal website & blog.

url: "https://ddtkey.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# i8n
languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
language_names:
  ru: Русский
  en: English

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# Social links
twitter_username: DDttKey
github_username:  DDtKey
facebook_username: 
linkedin_username: ddtkey
behance_username: 
instagram_username: ddttkey
medium_username: 
telegram_username: DDtKey
dribbble_username: 
flickr_username: 

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

#disqus_shortname:
#hyvor_talk_website_id:

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# formspree (contact form)
formspree_email: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination config
pagination:
  enabled: true
  debug: false
  per_page: 4
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archive
  permalinks:
    category: '/blog/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin
  - jekyll-polyglot
  - jekyll-archives
  - jekyll-email-protect

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# fix polyglot for jekyll 4+
sass:
  sourcemap: never


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
