about: About
author: Author
authors: Authors
categories: Categories
category: Category
current_page: current
education: Education
first_page: First
hi_i_am: Hi, I am
last_page: Last
post_by_author: Posts by this author
posted_by: Posted by
posts_from_category: Posts from category
projects: Projects
read: Read
recent_arcticles: Recent Articles
skills: Skills
useful_links: Useful Links
view_all: View All
work_exp: Work Experience
