about: Обо мне
author: Автор
authors: Авторы
categories: Категории
category: Категория
current_page: текущая
education: Образование
first_page: Первая
hi_i_am: Привет, я
last_page: Последняя
post_by_author: Публикации этого автора
posted_by: Опубликовал
posts_from_category: Публикации из категории
projects: Проекты
read: Читать
recent_arcticles: Свежие публикации
skills: Навыки
useful_links: Полезные ссылки
view_all: Смотреть все
work_exp: Опыт работы
